### ISSUE TITLE
How to set the special tokens with my dictionary in fairseq-preprocess?

### ISSUE THREAD

**Issue by js-lee-AI** [facebookresearch/fairseq#4294]
I wanna set special tokens like [BOS], [EOS], [SEP], [CLS] etc.
I couldn't set the special tokens with my own dictionary using `--srcdict` and `--tgtdict` in fairseq-preprocess.

1) What is default special tokens in fairseq vocabulary? 
2) And how to set my own special tokens in fairseq-preprocess?

Thanks

**Comment by gmryu** [comment]
You can find dictionray here: https://github.com/pytorch/fairseq/blob/main/fairseq/data/dictionary.py

If you are new and want to learn more about fairseq, please read through fairseq/fairseq_cli/train.py, preprocess.py, generate.py, interactive.py. Not necessary all of lines, but they really tell you the main flow of how fairseq works and a lot of useful fairseq classes and methods.

Embarrassing me, I have read those but I do not know there is any way to add "special" tokens with a normal fairseq.
In most case, says we want to add [SEP],[CLS],  raw data must already have those tokens inside. 
(like "A:I ate the apple.[SEP]B:you will regret it.[CLS]". You cannnot have bos,eos since fairseq appends them automatically)
If you already have a dict.txt, just add [SEP] and [CLS] at the top of it. (one in a line). And pass as --srcdict --tgtdict. 
They will not be special, but they are tokens as others. 
If you want your generated output not containing them, you have to write another python methods/scripts to get rid of them.

**Comment by js-lee-AI** [comment]
it was helpful. I'm closing the issue.
