### ISSUE TITLE
Preprocessing the COIN dataset for the VLM model

### ISSUE THREAD

**Issue by mozhdehrouhsedaghat** [facebookresearch/fairseq#4500]
Would you please add the script of preprocessing the COIN dataset required before feeding it into the VLM and VideoCLIP models? Many thanks!

**Comment by yyuncong** [comment]
Hi! Could you please share your solution to this issue with me? Thanks a lot!

**Comment by mozhdehrouhsedaghat** [comment]
Sure, the same code provided for preprocessing HowTO100M data also works for COIN. Just download the COIN videos and update <path_to_video_folder> in scripts/video_feature_extractor/how2/s3d.sh.

**Comment by yyuncong** [comment]
Thank you for the helpful reply! I followed your suggestions and extracted COIN features for training. However, I found that both zero-shot and fine-tuning give significantly worse results than the stats on their VideoCLIP paper. I'm wondering whether you have the same observations? Thank you!

**Comment by mozhdehrouhsedaghat** [comment]
No, I could reproduce the reported results.

**Comment by libo87** [comment]
@mozhdehrouhsedaghat 
By using the videoclip model, i reproduce the reported results too. But i found all the predicted label were '0', does't it mean the videoclip predict nothing? why class-0 should be counted

**Comment by bryant1410** [comment]
Hi. If this is the way of reproducing VideoCLIP results on the COIN Action Segmentation task, then I think the method considers parts of the video that should be ignored. If this is true, then the results may be a bit inflated.

The COIN metadata JSON file [follows a structure](https://github.com/coin-dataset/annotations#file-structure) indicates, for each video, where the region of interest starts and ends. My understanding is that these fields are ignored. They [aren't used in the code that loads this data](https://github.com/facebookresearch/fairseq/blob/bfd9dc6/examples/MMPT/mmpt/processors/dsprocessor.py#L703-L715), and neither in the S3D feature extraction method described in this issue. [The official script to download the COIN dataset](https://github.com/coin-dataset/annotations/blob/master/download_videos.py) also doesn't cut the videos to only consider this region of interest.

For example, the first video in the "testing" subset of COIN lasts 185 seconds but the region of interest goes from the second 20 to the second 134 (so it actually lasts around 114 seconds).

Considering more parts of the video entails more frames with class 0 being considered and thus more correctly predicted frames when computing the metrics since VideoCLIP tends to predict frames as belonging to class 0.

Maybe I'm missing something?
