### ISSUE TITLE
[LanguagePairDataset]: Simplest way of loading embedding vectors as input (Encoder)?

### ISSUE THREAD

**Issue by st-vincent1** [facebookresearch/fairseq#4587]
#### What is your question?
I'm experimenting with loading **embedding vectors** into an Encoder in the "transformer" architecture. My inputs would look like this:
`batch_size x embedding_dim x padded_input_length`

and my outputs would be standard TranslationTask outputs:
`batch_size x padded_input_length`

While the outputs are tokens, the inputs are already encoded embeddings (hence the extra dimension).

I'm fairly confident in modifying the `LanguagePairDataset` class to accept this input. However, I'm not sure how to change `load_langpair_dataset` within `fairseq/tasks/translation.py` to load numerical data of shape, as some helper functions used here (such as `load_indexed_dataset` within `fairseq/data/data_utils.py` presuppose token data and the use of a dictionary (which I will not need for the Encoder). 

What would be a minimal example/best way of going about loading this type of input? Perhaps the answer lies in using the `dataset_impl` argument?

Could I get some pointers? :)

#### Code

I'm happy to share any snippets of what I have so far if needed.

I'm using fairseq 0.12.2, installed with `pip install --editable ./` on Python 3.10.

**Comment by gmryu** [comment]
I assume you are using copies of `data/language_pair_dataset.py` and `tasks/translation.py`. (If you are not, copy them and modify the copy, not the origin)

Then, `fairseq-preprocess`ed data is numerical. Dictionaries are passed in `load_indexed_dataset` but they are not used here.
So please calm down a bit. I do not believe it is a wise choice to mess with `dataset_impl` as they are mostly meant to save memory / speed up during excution.

Actually one step back, do you really need to use `load_indexed_dataset`? 
If you do not require loading a huge amount of data via mmap, you can use your own script to load your binary data. 
(well, you can use `load_indexed_dataset` as well. In that case read through their implementation. They have some format to follow. Though I guess you want to start from `fairseq-preprocess`.)

The minimal way of creating a `LanguagePairDataset` is:
```
lines=["I am John.", "You are Alice."] # raw inputs.
src_tokens = [
        #each is a 1d LongTensor. pad, non-pad, length do not matter.
        fs_dict.encode_line( _str , add_if_not_exist=False).long()
        for _str in lines
]
src_lengths = [t.numel() for t in src_tokens]
# the same for tgt_tokens

LanguagePairDataset(
        src_tokens, src_lengths, src_dict,
        tgt_tokens, tgt_lengths, tgt_dict,
        left_pad_source=True, ...
)
```
A proof that you can use `list[torch.LongTensor]` instead of those fancy dataset. (may take more time during loading, but loading is seldom a bottle neck compared to training I belive)

**Comment by st-vincent1** [comment]
@gmryu, Thanks for the reply! I'm working on copies of course :)

I took your advice and looked away from `load_indexed_dataset` and `dataset_impl` and instead I just load the dataset directly in the `load_dataset` function within the `tasks/mytask.py` implementation. So far it seems to be working :)
