### ISSUE TITLE
MBART pretraining instructions and details

### ISSUE THREAD

**Issue by BramVanroy** [facebookresearch/fairseq#4713]
Pretraining code for MBART seems to be missing. Any help would be great with that respect, including preprocessing instructions, tokenization, hyperparameters. Such details are also missing from the [paper](https://aclanthology.org/2020.tacl-1.47.pdf).

In the paper in Section 2.2 under "Instance format" it is said that "for each instance of a batch" data is sampled from a language ID. But it is not clear to me whether that means that a batch can contain multiple languages, or that each sample in a batch is separately sampled for a language ID. 

cc @ngoyal2707 @mikelewis0

**Comment by gmryu** [comment]
"each instance of a batch" means a line of sentences. Since that line starts with ID like `<en>`, that whole line is written in that language (english if en).

A batch is made of multiple lines, so a batch can contain multiple languages.
I believe a line like `<en> I love apple. <fr> je déteste la tarte.` is not used in general. 
While, it does not mean a model cannot learn from it, but such task is simply more difficult while we can go around it by splitting lines ourselves.

**Comment by BramVanroy** [comment]
Thanks for the reply!
