### ISSUE TITLE
fairseq install error

### ISSUE THREAD

**Issue by kli017** [facebookresearch/fairseq#4843]
Hello, I met a error when I trying to install fairseq with cmd **pip3 install --editable ./"**
the error message like below:
`Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/likai/miniconda3/envs/fairseq/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/likai/miniconda3/envs/fairseq/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/likai/miniconda3/envs/fairseq/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 446, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "/tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/torch/__init__.py", line 191, in <module>
          _load_global_deps()
        File "/tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/torch/__init__.py", line 153, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/home/likai/miniconda3/envs/fairseq/lib/python3.8/ctypes/__init__.py", line 373, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /tmp/pip-build-env-da1j7k9z/overlay/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
`

### Environment
 - fairseq Version (e.g., 1.0 or main): 
 - PyTorch Version: 1.10.1+cu111
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source): pip3 install --editable ./
 - Python version: python3.8.13
 - CUDA/cuDNN version: cuda11.1
 - GPU models and configuration: A100

**Comment by Labyrintbs** [comment]
Same problems, with Environment

- PyTorch Version: 1.12.1+cu113
- OS (e.g., Linux): Linux
- How you installed fairseq (pip, source):
- Build command you used (if compiling from source): pip3 install --editable ./
- Python version: python3.8.13
- CUDA/cuDNN version: cuda11.3
- GPU models and configuration: GeForce GTX 1080 Ti

**Solved**, anyone with same problem can try with the pip flag **_--no-build-isolation_**
see https://lightrun.com/answers/h5py-h5py-source-build-can-only-find-system-installation-of-cython-not---user-or-venv

In my situation, it seems that due to environment setting or other things, pip install --editable uses exactly the system settings and not my conda environment, so it continuely uses the system environment and enhence can't find the cuda dll or other things to build ...(and take a long time to download dependecies)

**Comment by MovingKyu** [comment]
Thank you @Labyrintbs. you have saved my day.

**Comment by Nik-Kras** [comment]
I had the same problem, running on Linux server. Whenever I tried to install `fairseq` I got `Failed building wheel for fairseq`.
Aparently, the problem was in C++ compiler. Follow steps below, if you have Linux, you will just need to install g++:

1. Install / Update packages `sudo apt update && sudo apt install build-essential`
2. Check list of available g++ `apt search '^g\+\+-[0-9]+$'`
3. Install at least version 12 or later from the list of available versions `sudo apt install g++-12`

PS:
Here are error logs I used to get before this solution
```bash
 pip install fairseq
 
 ....
 
gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/include/python3.10 -c fairseq/clib/libbleu/libbleu.cpp -o build/temp.linux-x86_64-cpython-310/fairseq/clib/libbleu/libbleu.o -std=c++11 -O3
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141209 sha256=5f5d56effcc196ca1d5eb3fe94da5ead9ba550f6e5bf9d4f29b7454f624705fe
  Stored in directory: /root/.cache/pip/wheels/a7/20/bd/e1477d664f22d99989fd28ee1a43d6633dddb5cb9e801350d5
Successfully built antlr4-python3-runtime
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects
```

**Comment by qinghuanyyz** [comment]
> 我在 Linux 服务器上运行时遇到了同样的问题。每当我尝试安装时，我都会得到.当然，问题出在C++编译器中。请按照以下步骤操作，如果您使用的是 Linux，则只需安装 g++：`fairseq``Failed building wheel for fairseq`
> 
> 1. 安装/更新软件包`sudo apt update && sudo apt install build-essential`
> 2. 检查可用 g++ 的列表`apt search '^g\+\+-[0-9]+$'`
> 3. 从可用版本列表中至少安装版本 12 或更高版本`sudo apt install g++-12`
> 
> PS：这是我在此解决方案之前曾经获得的错误日志
> 
> ```shell
>  pip install fairseq
>  
>  ....
>  
> gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/include/python3.10 -c fairseq/clib/libbleu/libbleu.cpp -o build/temp.linux-x86_64-cpython-310/fairseq/clib/libbleu/libbleu.o -std=c++11 -O3
>       error: command 'gcc' failed: No such file or directory
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for fairseq
>   Building wheel for antlr4-python3-runtime (setup.py) ... done
>   Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141209 sha256=5f5d56effcc196ca1d5eb3fe94da5ead9ba550f6e5bf9d4f29b7454f624705fe
>   Stored in directory: /root/.cache/pip/wheels/a7/20/bd/e1477d664f22d99989fd28ee1a43d6633dddb5cb9e801350d5
> Successfully built antlr4-python3-runtime
> Failed to build fairseq
> ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects
> ```

我在linux服务器上遇到了和您之前相同的问题，“ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects”，请问您可以详细说一下，如何安装“g++：fairseqFailed building wheel for fairseq”吗，我对这里并不了解，十分感谢，

**Comment by NefelibataJay** [comment]
Find a way to update gcc and g++ to version 9 and above


> > 我在 Linux 服务器上运行时遇到了同样的问题。每当我尝试安装时，我都会得到.当然，问题出在C++编译器中。请按照以下步骤操作，如果您使用的是 Linux，则只需安装 g++：`` fairseq``Failed building wheel for fairseq ``
> > 
> > 1. 安装/更新软件包`sudo apt update && sudo apt install build-essential`
> > 2. 检查可用 g++ 的列表`apt search '^g\+\+-[0-9]+$'`
> > 3. 从可用版本列表中至少安装版本 12 或更高版本`sudo apt install g++-12`
> > 
> > PS：这是我在此解决方案之前曾经获得的错误日志
> > ```shell
> >  pip install fairseq
> >  
> >  ....
> >  
> > gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/include/python3.10 -c fairseq/clib/libbleu/libbleu.cpp -o build/temp.linux-x86_64-cpython-310/fairseq/clib/libbleu/libbleu.o -std=c++11 -O3
> >       error: command 'gcc' failed: No such file or directory
> >       [end of output]
> >   
> >   note: This error originates from a subprocess, and is likely not a problem with pip.
> >   ERROR: Failed building wheel for fairseq
> >   Building wheel for antlr4-python3-runtime (setup.py) ... done
> >   Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141209 sha256=5f5d56effcc196ca1d5eb3fe94da5ead9ba550f6e5bf9d4f29b7454f624705fe
> >   Stored in directory: /root/.cache/pip/wheels/a7/20/bd/e1477d664f22d99989fd28ee1a43d6633dddb5cb9e801350d5
> > Successfully built antlr4-python3-runtime
> > Failed to build fairseq
> > ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects
> > ```
> 
> 我在linux服务器上遇到了和您之前相同的问题，“ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects”，请问您可以详细说一下，如何安装“g++：fairseqFailed building wheel for fairseq”吗，我对这里并不了解，十分感谢，

**Comment by AchillesPlight** [comment]
I have this same issue, even when I use --no-build-isolation.

Are there any other ways to properly pip install fairseq?

(talkenv) C:\Users\achilles\talk>pip install fairseq --no-build-isolation
Collecting fairseq
  Using cached fairseq-0.12.2.tar.gz (9.6 MB)
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (1.16.0)
Requirement already satisfied: cython in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (3.0.10)
Collecting hydra-core<1.1,>=1.0.7 (from fairseq)
  Using cached hydra_core-1.0.7-py3-none-any.whl.metadata (3.7 kB)
Collecting omegaconf<2.1 (from fairseq)
  Using cached omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.4-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.4 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/92/b1/4f3023143436f12c98bab53f0b3db617bd18a7d223627d5030e13a7b4fc2/omegaconf-2.0.4-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.3-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.3 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/29/08/a88210c2c1aa0a3f65f05d8a6c98939ccb84b6fb982aa6567dec4e6773f9/omegaconf-2.0.3-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.2-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.2 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/72/fe/f8d162aa059fb4f327fd75144dd69aa7e8acbb6d8d37013e4638c8490e0b/omegaconf-2.0.2-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.1-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.1 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/86/ec/605805e60abdb025b06664d107335031bb8ebdc52e0a90bdbad6a7130279/omegaconf-2.0.1-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: regex in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (2024.5.15)
Collecting sacrebleu>=1.4.12 (from fairseq)
  Using cached sacrebleu-2.4.2-py3-none-any.whl.metadata (58 kB)
Requirement already satisfied: torch in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (2.4.0+cu124)
Requirement already satisfied: tqdm in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (4.66.4)
Collecting bitarray (from fairseq)
  Using cached bitarray-2.9.2-cp310-cp310-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: torchaudio>=0.8.0 in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (2.4.0+cu124)
Requirement already satisfied: numpy in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (1.23.5)
Collecting omegaconf<2.1 (from fairseq)
  Using cached omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
Collecting fairseq
  Using cached fairseq-0.12.1.tar.gz (9.6 MB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\achilles\talk\talkenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\achilles\talk\talkenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\achilles\talk\talkenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\achilles\talk\talkenv\lib\site-packages\setuptools\build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\achilles\talk\talkenv\lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "<string>", line 18, in write_version_py
      FileNotFoundError: [Errno 2] No such file or directory: 'fairseq\\version.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ZhengqingUUU** [comment]
> I have this same issue, even when I use --no-build-isolation.
> 
> Are there any other ways to properly pip install fairseq?
> 
> (talkenv) C:\Users\achilles\talk>pip install fairseq --no-build-isolation Collecting fairseq Using cached fairseq-0.12.2.tar.gz (9.6 MB) Preparing metadata (pyproject.toml) ... done Requirement already satisfied: cffi in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (1.16.0) Requirement already satisfied: cython in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (3.0.10) Collecting hydra-core<1.1,>=1.0.7 (from fairseq) Using cached hydra_core-1.0.7-py3-none-any.whl.metadata (3.7 kB) Collecting omegaconf<2.1 (from fairseq) Using cached omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq) has invalid metadata: .* suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.4-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.4 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/92/b1/4f3023143436f12c98bab53f0b3db617bd18a7d223627d5030e13a7b4fc2/omegaconf-2.0.4-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.3-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.3 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/29/08/a88210c2c1aa0a3f65f05d8a6c98939ccb84b6fb982aa6567dec4e6773f9/omegaconf-2.0.3-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.2-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.2 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/72/fe/f8d162aa059fb4f327fd75144dd69aa7e8acbb6d8d37013e4638c8490e0b/omegaconf-2.0.2-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.1-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.1 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/86/ec/605805e60abdb025b06664d107335031bb8ebdc52e0a90bdbad6a7130279/omegaconf-2.0.1-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.0-py3-none-any.whl.metadata (3.5 kB) Requirement already satisfied: regex in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (2024.5.15) Collecting sacrebleu>=1.4.12 (from fairseq) Using cached sacrebleu-2.4.2-py3-none-any.whl.metadata (58 kB) Requirement already satisfied: torch in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (2.4.0+cu124) Requirement already satisfied: tqdm in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (4.66.4) Collecting bitarray (from fairseq) Using cached bitarray-2.9.2-cp310-cp310-win_amd64.whl.metadata (35 kB) Requirement already satisfied: torchaudio>=0.8.0 in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (2.4.0+cu124) Requirement already satisfied: numpy in c:\users\achilles\talk\talkenv\lib\site-packages (from fairseq) (1.23.5) Collecting omegaconf<2.1 (from fairseq) Using cached omegaconf-2.0.6-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1._) ~~~~~~^ Please use pip<24.1 if you need to use this version. Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB) WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata: Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq) has invalid metadata: ._ suffix can only be used with `==` or `!=` operators PyYAML (>=5.1.*) ~~~~~~^ Please use pip<24.1 if you need to use this version. INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while. Collecting fairseq Using cached fairseq-0.12.1.tar.gz (9.6 MB) Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [14 lines of output] Traceback (most recent call last): File "C:\Users\achilles\talk\talkenv\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "C:\Users\achilles\talk\talkenv\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "C:\Users\achilles\talk\talkenv\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 149, in prepare_metadata_for_build_wheel return hook(metadata_directory, config_settings) File "C:\Users\achilles\talk\talkenv\lib\site-packages\setuptools\build_meta.py", line 368, in prepare_metadata_for_build_wheel self.run_setup() File "C:\Users\achilles\talk\talkenv\lib\site-packages\setuptools\build_meta.py", line 313, in run_setup exec(code, locals()) File "", line 27, in File "", line 18, in write_version_py FileNotFoundError: [Errno 2] No such file or directory: 'fairseq\version.txt' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

This link solves it: https://github.com/facebookresearch/fairseq/issues/5552#issuecomment-2430136730
